### ISSUE TITLE
Errors when I change the input file

### ISSUE THREAD

**Issue by kitiwaii** [Reyshyram/Dotfiles#10]
I changed the kb_layout in the input file to tr and it gave the errors in the screenshot
![screenshot_2024-11-26_02-31-32](https://github.com/user-attachments/assets/6bd0d589-7de9-4e3f-be55-55881d96b0c6)

**Comment by kitiwaii** [comment]
I solved the problem, the only problem was that I saved it differently with LibreOffice

**Comment by Reyshyram** [comment]
Oh, I was trying to figure out the problem, nice if you managed to fix it.

I didn't think anyone would be using my dotfiles 😅
Do they work well for you?

**Comment by kitiwaii** [comment]
In my opinion you have very nice dot files

**Comment by Reyshyram** [comment]
Thanks!
