### ISSUE TITLE
Keybinds

### ISSUE THREAD

**Issue by 4Bravo** [Reyshyram/Dotfiles#11]
Super + / to show all the keybinds seems to not work? And now I can't even open up my terminal because I don't know the key to press. please help

**Comment by Reyshyram** [comment]
What is your keyboard layout?

**Comment by 4Bravo** [comment]
when i made this post it was default US but now i changed it to PL

**Comment by Reyshyram** [comment]
Are you pressing the Super key + key right to the left of RShift?

**Comment by 4Bravo** [comment]
You mean RSHIFT + SUPER + LEFT ARROW
Right?

**Comment by 4Bravo** [comment]
Just accidentaly pressed SUPER + T and it opened the terminal, but could you tell me where is keybind config file located?

**Comment by Reyshyram** [comment]
I mean these keys. It works perfectly fine for me
![image](https://github.com/user-attachments/assets/c03d40d9-9d61-4e0e-9364-935e8d7b5e47)

The config files are located inside the usual hyprland config directory, which is `$HOME/.config/hypr`.
For the keybindings it simply is the keybinds.conf file

**Comment by Reyshyram** [comment]
I may have misconfigured something since I'm basically the only one using these dotfiles

**Comment by 4Bravo** [comment]
Fixed
