### ISSUE TITLE
Log in screen not working

### ISSUE THREAD

**Issue by 4Bravo** [Reyshyram/Dotfiles#12]
After using the script and rebooting it turned out that instead of booting into your log in screen it boots into classic arch linux terminal login screen and after logging in you have to manually type hyprland to run.
Tried rebooting few times
Tried removing everything and installing again
Even tried installing arch from scratch all over again still didnt work

**Comment by Reyshyram** [comment]
Are you using grub?

**Comment by 4Bravo** [comment]
yes I am using grub, also when i first installed your script (the first time it worked) I also had grub so i don't think it's the issue

**Comment by Reyshyram** [comment]
I guess the script's broken

**Comment by Reyshyram** [comment]
I don't have the time to look into it right now, I'll try to see what I can do later

**Comment by 4Bravo** [comment]
Thanks for your interest in my issue, see you soon ig

**Comment by Reyshyram** [comment]
I've tried an installation from scratch and everything worked, so I don't know what might be causing the issue. I guess you should try someone's else dotfiles

**Comment by 4Bravo** [comment]
ISSUE SOLVED:
sudo systemctl enable sddm
sudo systemctl start sddm

**Comment by Reyshyram** [comment]
That’s something that should be covered by the installation script, maybe you forgot to enter your password or you miss typed up t
