### ISSUE TITLE
Kitty colors & themes

### ISSUE THREAD

**Issue by 4Bravo** [Reyshyram/Dotfiles#15]
How to disable kitty's colors set by your dotfiles? I tried changing the kitty's theme using `kitty +kitten themes --reload-in=all` but after choosing the theme and running kitty it opens with that theme for a split second an instantly changes into your theme. I tried removing the `.cache/wal/colors-kitty.conf` but that doesn't work either. Also I wanted to ask you where is a config file located that makes the terminal show ">" on input instead of the default "[username@arch]"

**Comment by Reyshyram** [comment]
Remove
```
# Pywal
(cat ~/.cache/wal/sequences &)
```

from your .zshrc file and
```
# Pywal
include ~/.cache/wal/colors-kitty.conf
```
from your kitty configuration file.
Then you can modify zsh's configuration file to change the prompt that is being used.
